included:
  - App
  - Packages

excluded:
  - .build
  - .swiftpm
  - Packages/**/.build
  - Packages/**/.swiftpm

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - last_where
  - let_var_whitespace
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - switch_case_alignment
  - unneeded_parentheses_in_closure_argument

analyzer_rules:
  - unused_import

# Keep defaults reasonable for a starter codebase.
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

identifier_name:
  excluded:
    - id
    - URL
